import BookTest from "./bookTest.model.js";
import Admin from "./admin.model.js";
import GeneralCrop from "./generalCrop.model.js";
import Test from "./test.model.js";
import FarmerCrop from "./farmerCrop.model.js";
import Labtech from "./labtech.model.js";
import Plot from "./plot.model.js";
import TestResult from "./testResult.model.js";
import User from "./user.model.js";